[GENERAL]
refSeqs = gDNA.fasta.fai

# 1. 参考基因组序列轨道
[tracks.refseq]
urlTemplate = gDNA.fasta
storeClass = JBrowse/Store/SeqFeature/IndexedFasta
type = Sequence
category = Reference

# 2. 原始注释轨道 (NCBI)
[tracks.ref_annotation]
urlTemplate = ref_anno.sorted.gff.gz
storeClass = JBrowse/Store/SeqFeature/GFF3Tabix
type = CanvasFeatures
category = Annotation
key = NCBI Reference Annotation

# 3. 同源搜索结果轨道 (BLAST)
[tracks.homology]
urlTemplate = homology.sorted.gff3.gz
storeClass = JBrowse/Store/SeqFeature/GFF3Tabix
type = CanvasFeatures
category = Analysis
key = Homology Search (BLAST)
glyph = JBrowse/View/FeatureGlyph/Segments

# 4. 从头预测结果轨道 (Augustus)
[tracks.augustus]
urlTemplate = augustus.sorted.gff3.gz
storeClass = JBrowse/Store/SeqFeature/GFF3Tabix
type = CanvasFeatures
category = Analysis
key = Ab Initio Prediction (Augustus)

# 5. TATA Box 预测结果轨道 (PWM)
[tracks.tatabox]
urlTemplate = tata_box.sorted.gff3.gz
storeClass = JBrowse/Store/SeqFeature/GFF3Tabix
type = CanvasFeatures
category = Analysis
key = TATA Box Prediction
